### ISSUE TITLE
[Build error] Directory Typo

### ISSUE THREAD

**Issue by alexq-hh** [healthhackersER/CAMA-CORE-Example#31]
# Problem
As a developer I tried to run the project on a fresh Ubuntu install.
While starting the node.js server (npm run web) I get an build error.

# Solution
Rename directory from:
/CAMA-CORE-Example/Screens/FormMetainfo
to
/CAMA-CORE-Example/Screens/FormMetaInfo

# Goal
Initial build should work :)

# Additional Hints
At the moment I want to create a development VM and
review/validate the installation process.

**Comment by GundlackFelixDEV** [comment]
@ alexq-hh Thanks for the issue - very good description!
Fixed it and pull-request waiting #32 to be confirmed by review...
